TRAIN_WEIGHT = 0.9
EPOCH = 10
SEQ_LEN = 49
DIRECTORY = '/workspaces/quant-project/'
TRAIN_DATA_PATH = "stock_daily/stock_train.csv"
TEST_DATA_PATH = "stock_daily/stock_test.csv"
BATCH_SIZE = 32
LEARNING_RATE=0.00001
lstm_path="./model_lstm/epoch_"
transformer_path="./model_transformer/epoch_"
# save_path=lstm_path
SAVE_PATH = transformer_path
